# https://pre-commit.com/
# A framework for managing and maintaining multi-language pre-commit hooks.
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
    # Git style
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: check-vcs-permalinks
    - id: forbid-new-submodules
    - id: no-commit-to-branch
    - id: check-case-conflict

    # Common errors
    - id: end-of-file-fixer
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: check-yaml
    - id: check-json
    - id: check-merge-conflict
    - id: check-executables-have-shebangs

    # Cross platform
    - id: check-case-conflict
    - id: mixed-line-ending
      args: [--fix=lf]

    # Security
    - id: detect-aws-credentials
      args: ['--allow-missing-credentials']
    - id: detect-private-key

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.64.0
  hooks:
    - id: terraform_fmt
    - id: terraform_validate

- repo: https://github.com/Yelp/detect-secrets
  rev: v1.2.0
  hooks:
    - id: detect-secrets
