---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: demo
spec:
  owner: guests
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo
  annotations:
    github.com/project-slug: jnahelou/gcp-gke
spec:
  type: landing-zone
  lifecycle: production
  owner: guests
  dependsOn:
    - resource:default/demo-gke
    - resource:default/demo-project
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: demo-project
  description: Google Cloud project used to host demo resources.
spec:
  type: google_project
  owner: guests
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: demo-gke
  description: GKE Autopilot cluster used to host demo applications.
spec:
  type: google_container_cluster
  owner: guests
  dependsOn:
    - resource:default/demo-project
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: demo-gke--customer
  description: K8S namespace used to host demo resources.
spec:
  type: kubernetes_namespace
  owner: guests
  dependsOn:
    - resource:default/demo-gke
